const path = require('path');
const { readdirSync } = require('fs');
const keyValueService = require('../../services/keyValueService');
const { invalidateGuildConfig } = require('./runtimeRegistry');
const root = path.join(__dirname, '..', '..', 'slashcommand27');
function loadCommands(){const out=[]; for(const cat of readdirSync(root).filter(f=>!f.includes('.'))){for(const file of readdirSync(path.join(root,cat)).filter(f=>f.endsWith('.js'))){delete require.cache[require.resolve(path.join(root,cat,file))]; const c=require(path.join(root,cat,file)); const json=c.data?.toJSON?.()||{}; out.push({name:json.name,description:json.description||'No description',category:cat,file,adminsOnly:!!c.adminsOnly,ownersOnly:!!c.ownersOnly,options:json.options||[],schema:buildSchema(cat,json,c)});}} return out.sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
function buildSchema(cat,json,c){const base=['enabled','aliases','cooldown']; if(c.adminsOnly||['System','protection','Logs','Ticket','Broadcast'].includes(cat)) base.push('allowedRoles','deniedRoles','allowedChannels','deniedChannels'); if(cat==='Ticket') base.push('ticketSection'); if(cat==='Broadcast') base.push('broadcastScope'); return base;}
async function getSettings(guildId){return (await keyValueService.get('systemDB',`command_settings_${guildId}`))||{};}
async function saveSettings(guildId, settings){await keyValueService.set('systemDB',`command_settings_${guildId}`,settings); invalidateGuildConfig(guildId); return settings;}
async function getCommandState(guildId, name){const s=await getSettings(guildId); return Object.assign({enabled:true,aliases:[],cooldown:0,allowedRoles:[],deniedRoles:[],allowedChannels:[],deniedChannels:[]}, s[name]||{});}
async function canRunCommand(interaction, command){const st=await getCommandState(interaction.guildId, command.data.name); if(!st.enabled) return {ok:false,reason:'هذا الأمر معطل من لوحة التحكم.'}; const member=interaction.member; if(st.allowedChannels?.length && !st.allowedChannels.includes(interaction.channelId)) return {ok:false,reason:'هذا الأمر غير مسموح في هذه القناة.'}; if(st.deniedChannels?.includes(interaction.channelId)) return {ok:false,reason:'هذا الأمر ممنوع في هذه القناة.'}; const roles=[...(member?.roles?.cache?.keys?.()||[])]; if(st.deniedRoles?.some(r=>roles.includes(r))) return {ok:false,reason:'رتبتك ممنوعة من هذا الأمر.'}; if(st.allowedRoles?.length && !st.allowedRoles.some(r=>roles.includes(r))) return {ok:false,reason:'لا تملك رتبة مسموحة لهذا الأمر.'}; return {ok:true,state:st};}
module.exports={loadCommands,getSettings,saveSettings,getCommandState,canRunCommand};
