const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { ChannelType, PermissionsBitField } = require('discord.js');
const keyValueService = require('../../services/keyValueService');
const { SYSTEM_MODULES, COMMAND_CATEGORIES } = require('./moduleRegistry');
const { getGuildShortcuts, saveGuildShortcuts } = require('../../utils/shortcutUtils');
const { getWelcomeConfig, saveWelcomeConfig } = require('../../utils/welcomeUtils');
const { getTextScores, getVoiceScores } = require('../../utils/activityUtils');
const { getAdminConfig, saveAdminConfig, getPoints } = require('../../utils/adminPointsUtils');
function gkey(base,guildId){return `${base}_${guildId}`}
function maskToken(t){return t ? `${String(t).slice(0,6)}••••${String(t).slice(-4)}` : ''}
function getCommandList(client){const out=[]; for(const cmd of client.CookiesSlashCommands?.values?.()||[]){out.push({name:cmd.data.name,description:cmd.data.description||'',category:cmd.category||'General',adminsOnly:!!cmd.adminsOnly,ownersOnly:!!cmd.ownersOnly,options:cmd.data.options||[]})} return out.sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
async function getCommandSettings(guildId,client){const commands=getCommandList(client); const stored=await keyValueService.get('systemDB',gkey('command_settings',guildId))||{}; const shortcuts=await getGuildShortcuts(guildId); return commands.map(c=>({enabled: stored[c.name]?.enabled !== false, aliases: stored[c.name]?.aliases || (shortcuts[c.name]?[shortcuts[c.name]]:[]), cooldown: stored[c.name]?.cooldown||0, allowedRoles: stored[c.name]?.allowedRoles||[], deniedRoles: stored[c.name]?.deniedRoles||[], allowedChannels: stored[c.name]?.allowedChannels||[], deniedChannels: stored[c.name]?.deniedChannels||[], ...c}));}
async function saveCommandSettings(guildId,settings){await keyValueService.set('systemDB',gkey('command_settings',guildId),settings); const shortcuts={}; for(const [name,cfg] of Object.entries(settings||{})){ if(Array.isArray(cfg.aliases)&&cfg.aliases[0]) shortcuts[name]=cfg.aliases[0]; } await saveGuildShortcuts(guildId,shortcuts); return settings;}
async function getGuildResources(guild){await Promise.allSettled([guild.channels.fetch(), guild.roles.fetch()]); return { channels:guild.channels.cache.filter(c=>c.type!==ChannelType.DM).map(c=>({id:c.id,name:c.name,type:c.type,parentId:c.parentId})), categories:guild.channels.cache.filter(c=>c.type===ChannelType.GuildCategory).map(c=>({id:c.id,name:c.name})), roles:guild.roles.cache.filter(r=>r.id!==guild.id).map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position})).sort((a,b)=>b.position-a.position), members:guild.memberCount };}
async function getModuleConfig(guildId,moduleId){const mod=SYSTEM_MODULES.find(m=>m.id===moduleId); if(!mod) throw new Error('Unknown module'); if(moduleId==='welcome') return getWelcomeConfig(guildId); if(moduleId==='admin-points') return getAdminConfig(guildId); const value=await keyValueService.get(mod.namespace,gkey(mod.key,guildId)); return value || {};}
async function saveModuleConfig(guildId,moduleId,patch){if(moduleId==='welcome') return saveWelcomeConfig(guildId,patch); if(moduleId==='admin-points') return saveAdminConfig(guildId,patch); const mod=SYSTEM_MODULES.find(m=>m.id===moduleId); const current=await getModuleConfig(guildId,moduleId); const next={...current,...patch, guildId, updatedAt:new Date().toISOString()}; await keyValueService.set(mod.namespace,gkey(mod.key,guildId),next); return next;}
async function getDashboard(guild,client){const [resources,commands]=await Promise.all([getGuildResources(guild),getCommandSettings(guild.id,client)]); const modules=[]; for(const m of SYSTEM_MODULES){ const cfg=await getModuleConfig(guild.id,m.id).catch(()=>({})); modules.push({...m, enabled:!!cfg.enabled, count:Array.isArray(cfg.sections)?cfg.sections.length:Array.isArray(cfg.rules)?cfg.rules.length:0}); } const text=await getTextScores(guild.id); const voice=await getVoiceScores(guild.id); return {stats:{botStatus:client.ws.status===0?'online':'connecting',ping:Math.round(client.ws.ping),uptime:process.uptime(),guilds:client.guilds.cache.size,members:client.guilds.cache.reduce((n,g)=>n+(g.memberCount||0),0),commands:commands.length,enabledSystems:modules.filter(m=>m.enabled).length,openTickets:guild.channels.cache.filter(c=>/^ticket-/i.test(c.name||'')).size,textActivity:Object.values(text).reduce((a,b)=>a+b,0),voiceActivity:Object.values(voice).reduce((a,b)=>a+b,0)},modules,resources};}
async function getActivity(guild){return { text: await getTextScores(guild.id), voice: await getVoiceScores(guild.id), points: await getPoints(guild.id) };}
async function getBroadcast(guildId){const tokens=await keyValueService.get('BroadcastDB',gkey('tokens',guildId))||[]; const message=await keyValueService.get('BroadcastDB',gkey('broadcast_msg',guildId))||''; return {message,tokens:tokens.map((token,i)=>({id:i,masked:maskToken(token),hash:crypto.createHash('sha256').update(token).digest('hex').slice(0,12)}))};}
async function saveBroadcast(guildId,body){if(body.message!==undefined) await keyValueService.set('BroadcastDB',gkey('broadcast_msg',guildId),String(body.message).slice(0,4000)); if(body.removeAll) await keyValueService.delete('BroadcastDB',gkey('tokens',guildId)); return getBroadcast(guildId);}
function ensureManageGuild(member){return member?.permissions?.has(PermissionsBitField.Flags.ManageGuild)||member?.permissions?.has(PermissionsBitField.Flags.Administrator)}
module.exports={SYSTEM_MODULES,COMMAND_CATEGORIES,getDashboard,getGuildResources,getCommandSettings,saveCommandSettings,getModuleConfig,saveModuleConfig,getActivity,getBroadcast,saveBroadcast,ensureManageGuild};