const keyValueService = require('../../services/keyValueService');
const { getClient, invalidateGuildConfig } = require('./runtimeRegistry');
const namespaces={welcome:'systemDB',tickets:'ticketDB',applications:'applyDB',protection:'protectDB',logs:'logsDB',autoReply:'nadekoDB',suggestions:'suggestionsDB',feedback:'feedbackDB',giveaways:'giveawayDB',autoLine:'autolineDB',tax:'taxDB',broadcast:'BroadcastDB',activity:'systemDB',adminPoints:'systemDB',settings:'systemDB'};
const defaultConfig={welcome:{enabled:false,mode:'embed',color:'#787575',title:'مرحبا بك في {server}',message:'مرحبا {member}، نورت **{server}**!',dmEnabled:false,dmMessage:'أهلا {user}',embed:{timestamp:true},imageEditor:{enabled:false,backgroundUrl:'',avatar:{x:420,y:140,size:168,zoom:1,borderRadius:50,borderWidth:6,borderColor:'#ffffff'}}},tickets:{enabled:false,color:'#5865f2',sections:[]},applications:{enabled:false,positions:[]},protection:{systems:{antiBots:{enabled:false,limit:1,duration:60,punishment:'kick'},antiBan:{enabled:false,limit:3,duration:60,punishment:'removeRoles'},antiRoleDelete:{enabled:false,limit:2,duration:60,punishment:'removeRoles'},antiChannelDelete:{enabled:false,limit:2,duration:60,punishment:'removeRoles'}},logChannel:null,exemptRoles:[]},logs:{events:{}},autoReply:{enabled:false,replies:[]},suggestions:{enabled:false,cooldown:60,minLength:5,maxLength:1000,allowImages:true,upvoteEmoji:'👍',downvoteEmoji:'👎',starEmoji:'⭐'},feedback:{enabled:false,mode:'embed',rating:true,stars:5},giveaways:{enabled:true},autoLine:{enabled:false,channels:[],lineMode:'image'},tax:{enabled:false,mode:'embed',probotPercent:5,mediatorPercent:2},broadcast:{tokens:[],message:'',audience:'all'},activity:{enabled:true},adminPoints:{enabled:false,thresholds:[]},settings:{language:'ar',prefix:'!'}};
async function readModule(guildId, module){const stored=await keyValueService.get(namespaces[module]||'systemDB',`dashboard_${module}_${guildId}`); return {...(defaultConfig[module]||{}),...(stored||{})};}
async function writeModule(guildId,module,patch){const next={...(await readModule(guildId,module)),...patch}; await keyValueService.set(namespaces[module]||'systemDB',`dashboard_${module}_${guildId}`,next); await mirrorLegacy(guildId,module,next); invalidateGuildConfig(guildId); return next;}
async function mirrorLegacy(guildId,module,c){ if(module==='welcome'){await keyValueService.set('systemDB',`welcome_config_${guildId}`,c); if(c.channelId) await keyValueService.set('systemDB',`welcome_channel_${guildId}`,c.channelId); if(c.roleId) await keyValueService.set('systemDB',`welcome_role_${guildId}`,c.roleId);} if(module==='suggestions'&&c.channelId) await keyValueService.set('suggestionsDB',`suggestions_room_${guildId}`,c.channelId); if(module==='autoLine'){await keyValueService.set('autolineDB',`line_channels_${guildId}`,c.channels||[]); if(c.line) await keyValueService.set('autolineDB',`line_${guildId}`,c.line); await keyValueService.set('autolineDB',`line_mode_${guildId}`,c.lineMode||'image');} if(module==='tax'){if(c.channelId) await keyValueService.set('taxDB',`tax_room_${guildId}`,c.channelId); if(c.line) await keyValueService.set('taxDB',`tax_line_${guildId}`,c.line); await keyValueService.set('taxDB',`tax_mode_${guildId}`,c.mode||'embed');}}
async function guildResources(guildId){const client=getClient(); const g=client?.guilds.cache.get(guildId); if(!g) return {channels:[],categories:[],roles:[],members:[]}; await Promise.allSettled([g.channels.fetch(),g.roles.fetch()]); return {channels:g.channels.cache.filter(c=>c.type!==4).map(c=>({id:c.id,name:c.name,type:c.type})),categories:g.channels.cache.filter(c=>c.type===4).map(c=>({id:c.id,name:c.name})),roles:g.roles.cache.filter(r=>r.name!=='@everyone').map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position})).sort((a,b)=>b.position-a.position),members:[]};}
async function overview(guildId){const client=getClient(), g=client?.guilds.cache.get(guildId); const modules=Object.keys(defaultConfig).filter(k=>k!=='settings'); const configs=Object.fromEntries(await Promise.all(modules.map(async m=>[m,await readModule(guildId,m)]))); return {guild:g&&{id:g.id,name:g.name,icon:g.iconURL?.()},stats:{ping:client?.ws?.ping??0,uptime:process.uptime(),guilds:client?.guilds.cache.size??0,members:g?.memberCount??0,commands:client?.CookiesSlashCommands?.size??0,enabledSystems:modules.filter(m=>configs[m]?.enabled || configs[m]?.systems).length,openTickets:0,textActivity:0,voiceActivity:0},configs};}
module.exports={defaultConfig,readModule,writeModule,guildResources,overview};
