const SYSTEM_MODULES = [
  { id: 'settings', namespace: 'systemDB', key: 'server_settings', title: { en: 'Server Settings', ar: 'إعدادات السيرفر' }, description: { en: 'General guild preferences for ZEUS.', ar: 'تفضيلات السيرفر العامة في ZEUS.' }, route: '/settings' },
  { id: 'welcome', namespace: 'systemDB', key: 'welcome_config', title: { en: 'Welcome', ar: 'الترحيب' }, description: { en: 'Welcome channel, DM, embed and image designer.', ar: 'قناة الترحيب والخاص والإيمبد ومصمم الصورة.' }, route: '/welcome' },
  { id: 'tickets', namespace: 'ticketDB', key: 'ticket_dashboard', title: { en: 'Tickets', ar: 'التذاكر' }, description: { en: 'Ticket sections, support roles and logs.', ar: 'أقسام التذاكر ورتب الدعم والسجلات.' }, route: '/tickets' },
  { id: 'applications', namespace: 'applyDB', key: 'apply_settings', title: { en: 'Applications', ar: 'التقديمات' }, description: { en: 'Positions, questions and result channels.', ar: 'المناصب والأسئلة وقنوات النتائج.' }, route: '/applications' },
  { id: 'protection', namespace: 'protectDB', key: 'protection_config', title: { en: 'Protection', ar: 'الحماية' }, description: { en: 'Anti bot, ban, role and channel deletion settings.', ar: 'إعدادات منع البوتات والباند وحذف الرتب والقنوات.' }, route: '/protection' },
  { id: 'logs', namespace: 'logsDB', key: 'logs_config', title: { en: 'Logs', ar: 'السجلات' }, description: { en: 'Central event logs configuration.', ar: 'إعدادات مركزية لسجلات الأحداث.' }, route: '/logs' },
  { id: 'auto-reply', namespace: 'CookiesDB', key: 'replys', title: { en: 'Auto Reply', ar: 'الرد التلقائي' }, description: { en: 'Triggers, match modes, cooldown and embeds.', ar: 'المحفزات وأنماط المطابقة والتبريد والإيمبد.' }, route: '/auto-reply' },
  { id: 'suggestions', namespace: 'suggestionsDB', key: 'suggestions_config', title: { en: 'Suggestions', ar: 'الاقتراحات' }, description: { en: 'Suggestion channel, limits, reactions and line.', ar: 'قناة الاقتراحات والحدود والرياكشن والخط.' }, route: '/suggestions' },
  { id: 'feedback', namespace: 'feedbackDB', key: 'feedback_config', title: { en: 'Feedback', ar: 'الآراء' }, description: { en: 'Feedback room, rating and preview settings.', ar: 'قناة الآراء والتقييم والمعاينة.' }, route: '/feedback' },
  { id: 'giveaways', namespace: 'giveawayDB', key: 'giveaway_config', title: { en: 'Giveaways', ar: 'القيف أواي' }, description: { en: 'Giveaway defaults and active giveaway insight.', ar: 'إعدادات القيف أواي وحالة النشط منها.' }, route: '/giveaways' },
  { id: 'auto-line', namespace: 'autolineDB', key: 'autoline_config', title: { en: 'Auto Line', ar: 'الخط التلقائي' }, description: { en: 'Line channels, mode and image preview.', ar: 'قنوات الخط ونوعه ومعاينة الصورة.' }, route: '/auto-line' },
  { id: 'tax', namespace: 'taxDB', key: 'tax_config', title: { en: 'Tax', ar: 'الضريبة' }, description: { en: 'Tax channel, display mode and mediator percent.', ar: 'قناة الضريبة وطريقة العرض ونسبة الوسيط.' }, route: '/tax' },
  { id: 'activity', namespace: 'activityDB', key: 'activity_config', title: { en: 'Activity', ar: 'النشاط' }, description: { en: 'Text/voice leaderboard from ZEUS activity tracking.', ar: 'ترتيب الكتابة والصوت من تتبع ZEUS الحقيقي.' }, route: '/activity' },
  { id: 'admin-points', namespace: 'systemDB', key: 'admin_points_config', title: { en: 'Admin Points', ar: 'نقاط الإدارة' }, description: { en: 'Admin point rules, promotion limits and logs.', ar: 'قواعد النقاط وحدود الترقية والسجلات.' }, route: '/admin-points' },
  { id: 'broadcast', namespace: 'BroadcastDB', key: 'broadcast_config', title: { en: 'Broadcast', ar: 'البرودكاست' }, description: { en: 'Safe token management and broadcast message.', ar: 'إدارة آمنة للتوكنات ورسالة البرودكاست.' }, route: '/broadcast' }
];
const COMMAND_CATEGORIES = ['General','System','Ticket','apply','Broadcast','Feedback','Suggestions','Tax','Logs','Auto-reply','Auto-role','Autoline','protection','Giveaway','Nadeko'];
module.exports = { SYSTEM_MODULES, COMMAND_CATEGORIES };